# Generated by Django 5.1.6 on 2025-02-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='post_count',
            field=models.IntegerField(default=0),
        ),
    ]
